### ISSUE TITLE
Error in iot-nodejs/samples/WebApplicationSample 

### ISSUE THREAD

**Issue by LiuQhahah** [ibm-watson-iot/iot-nodejs#100]
root@liu-ThinkPad-Edge-E220s:/usr/local/software/iot-nodejs/samples/WebApplicationSample# npm install
root@liu-ThinkPad-Edge-E220s:/usr/local/software/iot-nodejs/samples/WebApplicationSample# npm start

> AngularIoTApp@0.0.0 start /usr/local/software/iot-nodejs/samples/WebApplicationSample
> node ./bin/www

sh: 1: node: not found

npm ERR! Linux 4.10.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! AngularIoTApp@0.0.0 start: `node ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the AngularIoTApp@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AngularIoTApp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AngularIoTApp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AngularIoTApp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/software/iot-nodejs/samples/WebApplicationSample/npm-debug.log

![error](https://user-images.githubusercontent.com/15814217/32054283-825f481a-ba90-11e7-9fc6-c22c3c653704.png)

**Comment by jeffdare** [comment]
Hi @LiuQhahah 

The program cannot find "node" in your system. Either the node is not installed in your system or node is not present in the PATH.

**Comment by LiuQhahah** [comment]
Thank you  !!!

**Comment by amitmangalvedkar** [comment]
Since this issue is not related to the client library, can we close it?

**Comment by LiuQhahah** [comment]
Yes
