### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by zafersn** [ibm-watson-iot/iot-nodejs#102]
Hi.  I would like to publish the mqtt topic in this project by following the directions in this repository. However, "var Client = require ('ibmiotf');" when I add it I get an error like this:  

Uncaught ReferenceError: require is not defined

**Comment by amitmangalvedkar** [comment]
@zafersn : Could you please elaborate the exact issue that you are facing? Are you implying that the library `ibmiotf` does not get detected?   
If so, have you set the `$NODE_PATH` variable to point to the destination where the npm modules are stored?   
Typically these are in the folder `/usr/lib/node_modules`  
Could you please set this and check if you are still getting this issue?

**Comment by jeffdare** [comment]
@zafersn 
Are you running this Javascript in Browser or in Node.js Env?

**Comment by zafersn** [comment]
hi @jeffdare  I wanted to run it in the browser. So I wanted to build an application that works in the browser. But I solved the problem, thank you very much for your help.

**Comment by jeffdare** [comment]
@zafersn 
Glad to know that you were able to solve. For using this library in browser, follow here - https://github.com/ibm-watson-iot/iot-nodejs#load-the-library-in-browser. 
And then include this in your project - `iotf-client-bundle.js` or `iotf-client-bundle-min.js`.

I am closing this issue. But if you further questions, please feel free to open it again.
