### ISSUE TITLE
WebApplicationSample instructions don't work

### ISSUE THREAD

**Issue by YasharF** [ibm-watson-iot/iot-nodejs#111]
Following the instructions at https://github.com/ibm-watson-iot/iot-nodejs/tree/master/samples/WebApplicationSample  the user does not get the expected results when pressing the Connect button, nothing happens from the users end.  Looking at the debug tab of the browser there is a error "failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED" in Chrome's console, and "WebSocket Error: Network Error 12007, The server name or address could not be resolved" in IE.  I tried on two different systems/setups:

Chrome case setup: Win10 bash/Ubuntu , NodeJS v10.7.0, private LAN
IE case: Windows Server 2012 R2, NodeJS v8.11.2, EC2 public cloud

I also tried deleting the app and recreating a new API key and got the same results.

**Comment by icraggs** [comment]
Hi.  Are you sure you have the correct orgid?  I tried this just now, and it worked.

**Comment by YasharF** [comment]
Just following the instructions in the above link.  Is setting the correct orgid part of it?

**Comment by icraggs** [comment]
You have to fill out the three fields:

1. OrgId - a Watson IoT Platform organisation
2. application key
3. auth token 

these have to already exist in yours or someone else's organisation.   If I don't fill out the three fields, I get a prompt to do so (in Chrome).

**Comment by YasharF** [comment]
I just retired, but still getting the same error.  Assuming that it is not a software bug as you mentioned, then it is probably a documentation/instruction issue on making sure to grab the right values form the right place in the console.  Either way, I can't spend more time on this.  Going to use a different platform.  Thanks for getting back to me.

**Comment by icraggs** [comment]
Ok, thanks.
