### ISSUE TITLE
need to compile the module to es5 ? 

### ISSUE THREAD

**Issue by alchemist107** [ibm-watson-iot/iot-nodejs#133]
I run into the problem of using this module in my node js backend server cause it's written in es6
so I had to compile it manually and introduce some new APIs so I can use it, so why not publish a new module compiled to es5 in npm ? to make it easier for new developers on the IBM Watson IoT platform  .

**Comment by durera** [comment]
I believe the release of 0.6.1 addresses this: https://www.npmjs.com/package/@wiotp/sdk/v/0.6.1

If you have any problems let me know.
