### ISSUE TITLE
ApiClient and RegistryClient not exposed

### ISSUE THREAD

**Issue by jeffdare** [ibm-watson-iot/iot-nodejs#147]
Why aren't those 2 clients exposed from here - https://github.com/ibm-watson-iot/iot-nodejs/blob/master/src/index.js

**Comment by jeffdare** [comment]
Is this worked upon?

**Comment by JonahIBM** [comment]
Thanks for raising this - I've now exposed those (and the other api clients) for you.

**Comment by jeffdare** [comment]
Thank you for the quick response

**Comment by jeffdare** [comment]
Can you please publish this to npm?
