### ISSUE TITLE
Vulnerability reported in @wiotp/sdk because of axios

### ISSUE THREAD

**Issue by davydnorris** [ibm-watson-iot/iot-nodejs#155]
Current release needs axios to be revved due to a high priority security issue in axios 0.19, which is fixed in axios > 0.21

**Comment by scottdickerson** [comment]
I tried forcing this with a resolution but couldn't due to wiotpsdk failing

**Comment by scottdickerson** [comment]
any updates on this one @JonahLuckett ?  We need it for a fixpack over the next 2 weeks

**Comment by JonahLuckett** [comment]
Hey Scott - sorry for the delay - will try and have a fix pushed tomorrow for you

**Comment by scottdickerson** [comment]
any more updates? @JonahLuckett

**Comment by herleraja** [comment]
we need to update the axios to 1.6.0. do we have any ETA on this issue ?
