### ISSUE TITLE
Clients only accept String payloads

### ISSUE THREAD

**Issue by knolleary** [ibm-watson-iot/iot-nodejs#18]
The client only accepts string payloads. Nothing in the documentation says an event payload must be a string. Speaking to Dave L, If the format of an event is not 'json', it is valid to send a binary payload as the event data.

**Comment by jeffdare** [comment]
Yes. That is the limitation from the client https://www.npmjs.com/package/mqtt#publish. So if the payload is not string, must send a 'buffer'.

**Comment by asmod3us** [comment]
Can we please mention this in the docs? I've opened an issue for it over at https://github.com/IBM-Bluemix/docs/issues/285.

**Comment by knolleary** [comment]
No. Your library should *not* be exposing the limitations of the underlying library. If someone passes you an Object, it takes one line of code for you to JSON encode it for them. Do the hard work so your user doesn't have to.
