### ISSUE TITLE
Client does not do anything with observe, update or cancel DM requests

### ISSUE THREAD

**Issue by robert17** [ibm-watson-iot/iot-nodejs#20]
I tried using the current ibmiotf library to go through the 4 DM requests (reboot, reset, fw download, fw update) and was unable to do the firmware actions with the client as it is currently. 
Missing functionality in the client is supporting passing requests to the client that are published to topics iotdm-1/observe, iotdm-1/device/update and iotdm-1/cancel.

I added a few things in my fork https://github.com/robert17/iot-nodejs:
1. _onDmRequest emits dmUpdate, dmObserve and dmCancel events in addition to dmAction which was already there
2. _onDmResponse case for NOTIFY_TOPIC response message
3. Changed respondDeviceAction to respondDeviceRequest and updated it to take an rc, so that it can be used to respond to dmAction, dmUpdate, dmObserve and dmCancel requests, which expect some different return codes (200, 202, 204).
4. Updated manage() to take deviceInfo. Is there some other way for a device to update its deviceInfo than using the manage call? I couldn't find one so I think manage needs to be able to take deviceInfo.
5. some DM samples that initiate DM request using API and handle the action and respond appropriately.

Opening an issue rather than a pull request because my code updates may be a little messy / probably don't want or need to take all of my commits.

**Comment by jeffdare** [comment]
@robert17 We are working on the same, currently for the nodejs library to support DM actions. Will be delivering it in a couple of days.
Thanks!

**Comment by jeffdare** [comment]
This functionality is already present in Device client. Closing this issue.
