### ISSUE TITLE
Does this client SDK support proxy?

### ISSUE THREAD

**Issue by NNM11** [ibm-watson-iot/iot-nodejs#21]
Hi,

Does this client SDK have auto support for client proxy such as HTTP_PROXY=http://<proxy-server>:port or HTTPS_PROXY or SOCKS_PROXY?

Thanks,

**Comment by jeffdare** [comment]
Hi @NNM11 
This client does not explicitly have support for proxy(HTTP/SOCKS). But if the network can support, this can work over that.

**Comment by amitmangalvedkar** [comment]
Closing this defect as there is no further response.
