### ISSUE TITLE
Not authorised error

### ISSUE THREAD

**Issue by nanowireUK** [ibm-watson-iot/iot-nodejs#22]
**Issue**
When connecting with incorrect credentials to IoTF the DeviceClient instance will retry indefinitely despite there being no chance of success. Unable to catch the Not Authorised error and force a disconnect() since that function itself contains an isConnected() check.

**Potential solution**
Need to be able to call a function that prevents further retry attempts.

**Context**
I have an application that acts as a TCP gateway to IoTF. On a client establishing a TCP connection and receiving a header packet it uses that information to create a new device client instance. The incoming credentials are supplied by the client and as such could be incorrect.

**Comment by jeffdare** [comment]
@nanowireUK Thanks for reporting this issue. 
So if its an unauthorized error, it makes no sense to reconnect. I will check the code and fix this issue.

**Comment by nanowireUK** [comment]
@jeffdare Retrying may still make sense for some applications (for example an instance of the application is only ever going to attempt to connect one device) so not sure it's good to change the behavior for everyone.

Simply adding the ability to catch the error (already possible) and then providing a function that stops any further retry attempts would be useful. Currently you can't call disconnect() since it isn't actually connected.

**Comment by yutter** [comment]
Did the above issue ever get resolved? I am still seeing this problem and could really do with a solution
