### ISSUE TITLE
For multi node configuration iam facing Iotfclient is offline. Retrying connection

### ISSUE THREAD

**Issue by MuralikrishnaM** [ibm-watson-iot/iot-nodejs#23]
Hi Iam murali, iam developing a chat application using mqtt with this codebase. i have deployed the application on bluemix with 2 instances, and my client configuration looks like this
var appClientConfig = {
	"org" : "xxxx",
	"id" : "iotf-service",
	"auth-key" : "xxxx",
	"auth-token" : "xxxx!xxxx",
	"type " : "shared"
}
and iam testing the application with 2 mobiles. one mobile can send and receive the message. where as other mobile can only send, but not receiving, when i checked the backed, its showing , 
2016-04-22T11:45:11.315+0800
[App/0]
err
Iotfclient is offline. Retrying connection
2016-04-22T11:45:24.357+0800
[App/1]
err
Iotfclient is offline. Retrying connection

can you please guide me what iam missing for mult node configuration

**Comment by jeffdare** [comment]
Hi @MuralikrishnaM,

For the shared subscription to work on the mobile, it must have the same "id" and the type must be shared. Then the clients will work in the shared subscription(multi node) mode. If the type is not shared, then as the ids are same, only one client will connect and the other will be offline. 

But for a chat application, I think you will need all the clients to get the events, so shared subscription may not fit there. As with shared subscription, only one node will get the message. If that is the intended purpose, then shared subscription is good. 

Please let us know if you have any questions.
Thanks!
