### ISSUE TITLE
Shared subscription disconnects other appClient

### ISSUE THREAD

**Issue by wilcollins** [ibm-watson-iot/iot-nodejs#28]
Only a single connection is allowed when connecting multiple appClients configured with shared subscriptions, the other is disconnected. 

```
var appClientConfig = {
	"org": BLUEMIX_ORG_ID,
	"id" : BLUEMIX_APP_ID,
	"auth-key" : BLUEMIX_AUTH_KEY,
	"auth-token" : BLUEMIX_AUTH_TOKEN,
	"type " : "shared"
}
```

**Comment by jeffdare** [comment]
Hi @wilcollins 
I just tried sharedSubscription sample at my end. The shared subscription in the Node.js client does work. 

Did you extend your sample from samples/sharedSubscriptionSample.js ? Please ensure 2 things

1. The "_id_" in the config must be same in all the instances. You can provide any unique value to this, as long as its the same between the programs.
2. The "_type_" must be _shared_. 

Please let me know if you still have issues.

**Comment by wilcollins** [comment]
Both instances use the appClientConfig from above with the same initialized BLUEMIX_* properties, so yes, I am using the same ``id`` for both instances of the appClient and each has ``type`` of _shared_

**Comment by wilcollins** [comment]
I had looked at ``samples/sharedSubscriptionSample.js`` used it for scaffolding but I just ran it and confirmed it is working with multiple clients.
