### ISSUE TITLE
Support custom device actions

### ISSUE THREAD

**Issue by zywind** [ibm-watson-iot/iot-nodejs#33]
I wonder if you have plans to support custom device actions specified here: https://docs.internetofthings.ibmcloud.com/devices/device_mgmt/custom_actions.html.
Thanks.

**Comment by jeffdare** [comment]
Hi @zywind 
Yes, this is in plans, we will implement this soon. Will keep you posted. 

Thanks!

**Comment by nkolban** [comment]
See also:
http://stackoverflow.com/questions/41900191/registering-support-for-a-custom-device-management-extension-in-node-js-javascri

Any update on this issue?

**Comment by jeffdare** [comment]
This is available from ibmiotf@0.2.30
