### ISSUE TITLE
keep throwing  [BaseClient:connect] Iotfclient is offline. Retrying connection

### ISSUE THREAD

**Issue by swizardlv** [ibm-watson-iot/iot-nodejs#34]
I am using iotf nodejs client. after connected it keeps throwing ' [BaseClient:connect] Iotfclient is offline. Retrying connection' message. How can I get this debug and fixed?  thanks.

**Comment by Lokesh-K-Haralakatta** [comment]
Hi,
It's warning message being logged on the console when ever client gets offline from the Platform. The moment it gets connected, you'll see the Client Connected Message. If you are seeing this message continuously, then your client is still in offline state. Check the credentials used and try again!

**Comment by swizardlv** [comment]
hi @Lokesh-K-Haralakatta , thanks for replying. I got the connected info. so I think the credentials are correct. after a while it keeps throwing out the warnings.
```
IOT platform connected
[BaseClient:connect] Iotfclient is offline. Retrying connection
```

**Comment by jeffdare** [comment]
Hi @swizardlv 
Do you have another instance of the same program running? This will also be caused when you have 2 clients having same ID trying for connection. It will keep connecting and disconnecting continuously.

**Comment by swizardlv** [comment]
@jeffdare Yes, I have. You mean I need to use different application Id?

**Comment by swizardlv** [comment]
@jeffdare i use uuid as the application id, seems fixed this issue. thanks.

**Comment by sgruse** [comment]
Thank you! This is solved the issue for me as well but I have a question for anyone who can answer:

Can you please explain why using "uuid" or "Date.now()" is the solution for the "id" configuration property. When reading the docs, the ID property is supposed to represent the deviceID: 

var config = {
    "org" : "organization",
    "id" : "deviceId",
    "domain": "internetofthings.ibmcloud.com",
    "type" : "deviceType",
    "auth-method" : "token",
    "auth-token" : "authToken"
};

var deviceClient = new Client.IotfDevice(config);

How does setting the "id" property to a random int solve this problem. Why was it labeled as deviceID for functionality that can be used to CRUD devices with different ID's? Any information would be helpful, thanks!

**Comment by jeffdare** [comment]
Hi @swizardlv 

For connecting your **device**, you must use the Device ID that you use to register in the Watson IoT. 

For **Applications**, you can use any unique identifier for the field "id" to connect. So you can use uuid or Date.now().

**Comment by nrkhara** [comment]
Hello. I was searching for the same problem and landed on this page. I'm using the Cloudfoundry Boilerplate Apllication of IBM bluemix. In that, in the watson iot platform i have 2 api keys both have the role as "Standard application" which are both connected to the Bluemix Application. Now there are 2 things that are happening. 
1 My device is sending some data on to the BLuemix cloudant data base and second
2 I'm sending data from node red to the device. 
But i'm getting the error that [BaseClient:connect] Iotfclient is offline. 
So are the 2 watson iot services are clashing? if yes what can i do to make this 2 way communication flow work?
I changed the Device ID to any random integer number in the ibmiot node but that doesn't work.
can someone suggest me something?
Thank you.

**Comment by jeffdare** [comment]
Hi @nrkhara 
No, you can safely use 2 Watson IoT services in the same Node-RED flow. I feel in your case, you are specifying the Application ID property. For an organization in Watson IoT Platform, you cannot have 2 connections having the same Application ID, as that uniquely identifies the application. So you will get errors - Client disconnected, client is offline etc. 

In Node-RED, if you will leave the field blank, the node will auto-generate a unique ID for you, or if you want to specify please specify unique IDs for all the app nodes. 

Please let us know if you have any questions. 

Jeffrey

**Comment by nrkhara** [comment]
I'll share the details with you. Thanks for the reply. 
I'm using a Nodemcu ESP as an device to connect with the Default Cloud Foundry App of IBM Bluemix. By default the iotf service has one API key which is bound to the Application. Now i want to send device commands to the ESP via Bluemix from Node red. So first tried the ibmiot output node with the Bluemix Service method of authentication. On the Nodemcu end it receives the commands the prints the payload. All this is working fine when i'm using node red launching from bluemix app online. However i want the same to work on node red which is installed locally on my PC. For communicating locally using the ibmiot node i have read that we haveto read the API key authentication method. So i created a custom API in the iotf service and used that credentials to communicate with my APP. It works fine on node red which is hosted by ibm, but shows "unable to verify first certificate, iotfclient is offline." 
I'm pretty sure that there is some fundamental error that i'm missing as the same flow is working on node red which is hosted on the Bluemix acocunt. I also updated my nodejs and node red to the latest available versions, still the same error on the cmd line. 
Please spot a flaw.
Thank you.
