### ISSUE TITLE
How to connect mobile app to IBM IoT platform using IoTF nodejs library

### ISSUE THREAD

**Issue by somnathbm** [ibm-watson-iot/iot-nodejs#36]
Hi. I'm on a Cordova project. I'm using **Ionic framework 2** (_Typescript_) on the front-end to build the apps. What I can't understand is how should I use the **IBM IOTF** library (for NodeJS) to connect the app to the IBM IOT. 
FYI, the app is successfully connected to Bluemix service using (cordova **ibm-mfp-core** plugin).
1. Shall I use it as a seperate NodeJS file to be used from the backend (not in the build process)?
2. Shall I use it as browserified bundled JS in the build process ?

I have tried to load both bundled version of app code (produced by Ionic) and IBM IOTF library. But in this way the app stops working. I'm wondering if its possible to use multiple bundled file inside a single application.

**Comment by jeffdare** [comment]
Hi @somnathbm 
For the mobile app, it will good to bind this library as the node.js dependency. When you say, the app stops working, what happens? Does the connection drop? If possible, can you please give the logs for this. 

Thanks!

**Comment by Vincentjonssonqi** [comment]
I am experiencing a similar issue! I am building an app with Ioinc 2 and Angular2 and if I add the bundled version of this library to the project and try to import it I get no errors. But the moment I initialize it or just try to console the IBMIoTF variable, the entire app just stop loading. There are no errors but the app is no longer loaded in the browser.

**Comment by Vincentjonssonqi** [comment]
Okay I found a solution to why.. I addpted the answer provided in this post https://stackoverflow.com/questions/43833895/how-to-include-js-file-in-ionic-3 to how I was importing this lib and now it works

**Comment by jeffdare** [comment]
Thanks @Vincentjonssonqi. @somnathbm Are you still facing this issue? Please let us know.

**Comment by jeffdare** [comment]
Closing this issue. @somnathbm if you still have this issue, please feel free to reopen.
