### ISSUE TITLE
MQTT connection is unstable

### ISSUE THREAD

**Issue by joelmarty** [ibm-watson-iot/iot-nodejs#39]
Hi, when using the Gateway client, I can notice frequent losses of connection to a Watson IoT instance.

This is especially painful since the handling of errors is done through `on('error')` event handlers and the MQTT.js' `publish` callback is hidden. Is there any chance to either improve the connection stability or allow the usage of callbacks on the publish\* methods ?

**Comment by jeffdare** [comment]
Hi @joelmarty 
I have merged your PR and the callbacks are now active for the publish calls. So you can use that to track the errors.

Also, do you still see the frequent connection disconnects to Watson IoT?

**Comment by joelmarty** [comment]
We do not see them as often, and also the uses of callbacks makes it less of an issue.

When do you think a new release will be published?

**Comment by jeffdare** [comment]
It already published to npm.. Version - ibmiotf

**Comment by joelmarty** [comment]
npmjs only displays version 0.2.25 as the last version. I saw you edited the package.json but somehow npmjs doesn't pick up the change

**Comment by jeffdare** [comment]
In npm, even I observed that the version is not reflecting the latest change. But when you install `npm install ibmiotf` from the command line, it does give you the latest version (i.e) 0.2.27. There is some bug in npm.
Thanks!!

**Comment by joelmarty** [comment]
Thanks for the clarification. I'm closing this :+1:
