### ISSUE TITLE
callbacks from mqtt lib hidden away

### ISSUE THREAD

**Issue by joelmarty** [ibm-watson-iot/iot-nodejs#40]
The callbacks that the MQTT library accepts in its api for publish() are hidden by the methods defined in the various clients.

It cripples the library greatly since we cannot programmatically react upon the publication of a message and the only remaining error recovery mechanism is the 'error' event, which tends to hide the context in which the error happened (which event was being published, how many more messages to publish...)

**Comment by jeffdare** [comment]
Hi @joelmarty 
Thanks for raising this issue. I will be merging your PR.
