### ISSUE TITLE
Please provide a code sample: How to "Load the library in browser"

### ISSUE THREAD

**Issue by thomassuedbroecker** [ibm-watson-iot/iot-nodejs#48]
Can you please provide a sample how to use what is written in the documentation "https://github.com/ibm-watson-iot/iot-nodejs#load-the-library-in-nodejs--browserify"?

**Comment by jeffdare** [comment]
The sample is provided - https://github.com/ibm-watson-iot/iot-nodejs/tree/master/samples/WebApplicationSample
