### ISSUE TITLE
Promise support for pub/sub calls/events

### ISSUE THREAD

**Issue by somnathbm** [ibm-watson-iot/iot-nodejs#52]
Its just a question: Does the pub/sub methods/events like `subscribeToDeviceEvents()`, `subscribeToDeviceStatus()` etc. methods and `connect`, `disconnect`, `deviceEvent` etc. events support Promise API?

Seemingly they are not, but device management APIs do supports Promise API as I have found here

https://github.com/ibm-watson-iot/iot-nodejs/blob/master/samples/api.rst

**Comment by jeffdare** [comment]
Hi @somnathbm 
Currently the MQTT calls like subscribeToDeviceEvents, subscribeToDeviceStatus do not support Promises. All the ReST apis have promises support.
