### ISSUE TITLE
Deprecation warnings in node v6.9.5

### ISSUE THREAD

**Issue by simonmcl** [ibm-watson-iot/iot-nodejs#61]
Importing this module into a node app running v6.9.5 and higher (haven't tested lower) causes a very large stacktrace of deprecation warnings to appear in the console. 

Its coming from a module called `bufferutil` which is ultimately a dependency of `mqtt`, which this module has a dependency on. The version of `mqtt` being used, is using a version of a module, where an old version of `bufferutil` is being used.

`bufferutil` is listed as an optional dependency, so the issue has a work around to call `npm install --no-optional`. But `bufferutil` has been moved to a `devDependency` in later versions, it would be great if you could update the version of `mqtt` to avoid having to do this, and for future devs to not have to debug the stacktrace.

**Comment by jeffdare** [comment]
Hi @simonmcl 
The `mqtt` has moved to the latest version. You should not be seeing the warning messages now. 

Thanks!

**Comment by jeffdare** [comment]
Hi @simonmcl 
I am closing this issue, but if you encounter this issue again, please feel free to open another issue.
