### ISSUE TITLE
Where do I browse the events sent by the device? 

### ISSUE THREAD

**Issue by abhisheksoni27** [ibm-watson-iot/iot-nodejs#64]
I have successfully implemented the API, but can't figure out where the messages are actually sent to. 

Also, where can I set the commands that the device can receive?

**Comment by Lokesh-K-Haralakatta** [comment]
Hi Abhishek,
The events that you send using API goes to Watson IoT Platform. On Watson IoT Platform, you should have the device registered already and you should be able to see the events getting received by the device to which you send.
To receive the command by the device, you need to subscribe for the required commands in your device client program.
I hope this helps, if you need any further details/assistance, let us know.

Thx,
Loki...

**Comment by abhisheksoni27** [comment]
I want to know how to send a command to the device.

**Comment by Lokesh-K-Haralakatta** [comment]
You need to have ApplicationClient and use the method publishDeviceCommand present in ApplicationClient.js

**Comment by abhisheksoni27** [comment]
I'll check it out. Thanks!
