### ISSUE TITLE
Bidirectional  Mqtt  communication !

### ISSUE THREAD

**Issue by AnisBH** [ibm-watson-iot/iot-nodejs#65]
Hi Lokesh :)

Please I want to establish a bidirectional communication between two devices. 

Please review the following picture where I present the requested architecture:

![image](https://cloud.githubusercontent.com/assets/6696712/24445588/add1c72e-146a-11e7-85fb-7a590ee11dee.png)

Thanks Lokesh, 

Anis bh

**Comment by Lokesh-K-Haralakatta** [comment]
Hi Anis,

Can you please elaborate on your use case? 
What are you trying to achieve with the bidirectional communication?
What is the role of the Raspberry Pis?

Answers to these questions will help in assisting in achieving the scenario using our IoT Platform and Client Libraries.

Thx..,

Loki..

**Comment by amitmangalvedkar** [comment]
Closing this issue as there is no response.
