### ISSUE TITLE
Application Client - additional api calls for device state functions

### ISSUE THREAD

**Issue by SoumyaSundar** [ibm-watson-iot/iot-nodejs#68]
In order to use the api calls implemented in the Application client, it would be very useful to have the entire response object to be returned in the successful fetch to capture the status codes as well as the returned object.

**Comment by bryancboyd** [comment]
Hi @SoumyaSundar.  What type of information from the response would you like to have, and what is the use case you are trying to achieve?  I think the best approach would be to continue our current approach of returning parsed data for the API wrappers, but we could certainly include some additional information as a 2nd parameter to the resolve().

**Comment by SoumyaSundar** [comment]
Hi @bryancboyd, when we call this api from react application at that time just the data is sufficient but for test cases we need the status codes and in general for troubleshooting issues we might need the entire object.

**Comment by bryancboyd** [comment]
Let's consider just the error case, as a first step.  Will the reject() from callApi give enough information to successfully troubleshoot a failed response?

**Comment by SoumyaSundar** [comment]
Hi Bryan,
I've updated the issue title and going to use this number to create and publish the branch.

Thanks,
Soumya.

**Comment by bryancboyd** [comment]
I just merged the branch; closing the issue 👍

**Comment by SoumyaSundar** [comment]
Ok, thanks.
