### ISSUE TITLE
Ionic iOS :  Iotfclient is offline and connection timed out even when token auth succeeded

### ISSUE THREAD

**Issue by lotus91** [ibm-watson-iot/iot-nodejs#79]
I am using **iot-nodejs** library in an ionic project and I'm connecting as an **IotfDevice**.
Everything works perfectly on Android, but when it comes to iOS, I get a connection timeout : 

`[Warning] [BaseClient:connect] Iotfclient is offline. Retrying connection (console-via-logger.js, line 173)
[Debug] [BaseClient:connect] Retry in 3 sec. Count : 1 (console-via-logger.js, line 173)
[Info] [BaseClient:onClose] Connection was closed. (console-via-logger.js, line 173)
[Warning] [BaseClient:connect] Iotfclient is offline. Retrying connection (console-via-logger.js, line 173)
[Debug] [BaseClient:connect] Retry in 3 sec. Count : 2 (console-via-logger.js, line 173)
[Info] [BaseClient:onClose] Connection was closed. (console-via-logger.js, line 173)`

No other devices are connected on the same ID. When I check the logs on the dashboard of **https://myOrg.internetofthings.ibmcloud.com/dashboard**, the device gets authenticated successfully and then it enters the connection timeout : 

`Closed connection from 195.212.29.58. The connection timed out.	May 10, 2017 2:25:36 PM
Token auth succeeded: ClientID='d:9pxax0:Phone:Phone7', ClientIP=195.212.29.58	May 10, 2017 2:25:15 PM
`
I tried changing the **Content-Security-Policy** to add the **wss://** in my **index.html** meta, and add a bigger timeout but no luck.

Any idea what can be causing this issue ?

**Comment by amprasanna** [comment]
@lotus91 - Can you please confirm if you are still experiencing this Time Out issue

**Comment by amitmangalvedkar** [comment]
Closing this issue, @lotus91 can reopen it if she is still experiencing this issue
