### ISSUE TITLE
Device state api calls from node js application posting form data

### ISSUE THREAD

**Issue by SoumyaSundar** [ibm-watson-iot/iot-nodejs#80]
Iot-nodejs uses axios for sending xhr or http requests. 

Device state api calls will be called from browser or node environment. Current api calls implementation supports the calls invoked only from the browser. 

Axios http adaptor implementation doesn't support form data upload.

Additonal changes are required in callFormDataApi() to support calls from node application.

**Comment by jeffdare** [comment]
Device State has been implemented with the multi-part post and is available from version 0.2.39.
Closing this issue.
