### ISSUE TITLE
keep throwing [BaseClient:connect] Iotfclient is offline. Retrying connection

### ISSUE THREAD

**Issue by Channabasawa** [ibm-watson-iot/iot-nodejs#88]
@jeffdare even inspite of using unique id i keep getting this following error

[DeviceClient:publish] Client is not connected
10 Jul 12:07:58 - [error] [wiot:connectionPool:getClient] [DeviceClient:publish] Client is not connected
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onClose] Connection was closed.

I have tried to run it multiple times but it keeps giving me the same error.
can you plz help out with this?

:)Here I am trying to send real time data from my laptop to bluemix cloud using node-red.

**Comment by Channabasawa** [comment]
speaking with reference to bellow issue

https://github.com/ibm-watson-iot/iot-nodejs/issues/34

**Comment by jeffdare** [comment]
Hi @Channabasawa 
Can you please check if the MQTT port(1883/8883) is not blocked in your network.

**Comment by Channabasawa** [comment]
Yes the port was blocked.Thank you Sir now the problem is solved

**Comment by jeffdare** [comment]
Issue was with the port being blocked. Closing this issue.

**Comment by aditiagarwal1** [comment]
how do I check if the MQTT port(1883/8883) is blocked on my raspberry pi?

**Comment by aditiagarwal1** [comment]
@jeffdare @Channabasawa how do I check if the MQTT port(1883/8883) is blocked on my raspberry pi?

**Comment by jeffdare** [comment]
Most probably it will not be blocked by your raspberry pi, it will be blocked at your network level or your firewall. Check with your network admins, for blocked ports. 
Easy test to see it the port is blocked, do a telnet and check you can connect(you can replace the orgid with your orgid). 

```
telnet u5uw0v.messaging.internetofthings.ibmcloud.com 1883
telnet u5uw0v.messaging.internetofthings.ibmcloud.com 8883
```

**Comment by jeffdare** [comment]
Most probably it will not be blocked by your raspberry pi, it will be blocked at your network level or your firewall. Check with your network admins, for blocked ports. 
Easy test to see it the port is blocked, do a telnet and check you can connect(you can replace the orgid with your orgid). 

```
telnet u5uw0v.messaging.internetofthings.ibmcloud.com 1883
telnet u5uw0v.messaging.internetofthings.ibmcloud.com 8883
```

**Comment by aditiagarwal1** [comment]
@jeffdare I did the telnet the port is not blocked and I am still getting the same errors. 

I am doing a tutorial of simulating a doorbell camera and am on the part where the user presses the doorbell and a picture of their face is sent to the Cloudant database in Bluemix.  So far, I have three flows. Two flows (Process Doorbell flow and Send Picture flow) are onNode-RED on my raspberry pi and the other flow (Retrieve Picture flow) is in Node-RED on Bluemix. This is what is supposed to happen: The Process Doorbell flow should send an IBM IoT visitorAlert event message to Node-RED on Bluemix (Retrieve Picture Flow) which should, in turn, send an IBM IoT sendPicture command message back to Node-RED on Raspberry Pi (Send Picture Flow).  This will eventually create a Base64 encoded image string, package it up with the filename, length and status into a payload that gets sent to Cloudant in Bluemix by the insertPicture node.  I would see if it worked by going to the Bluemix Cloudant dashboard. I think I am having trouble connecting the flow on the pi to the flow on Bluemix and back.

However, when I deploy these flows and test if they work, I get errors in all Node-RED flows. In particular, these errors on the raspberry pi Node-RED flows are: "Error stopping node: Error: [BaseClient: disconnect] Client is not connected" and "[ApplicationClient: publish] Client is not connected".

The errors on the Bluemix Node-RED flow are: "Error stopping node: Error [BaseClient: disconnect] Client is not connected" and "Error: Connection refused: Not authorized".

Do you know what the issue/issues could be?

**Comment by Nivetha272003** [comment]
sir i dont know how to check whether mqtt server is blocked or not

**Comment by jeffdare** [comment]
@Nivetha272003 The Watson IoT platform is deprecated now. Please follow this - https://cloud.ibm.com/docs/IoT?topic=IoT-deprecation
