### ISSUE TITLE
listAllDevicesOfType API call only returns 100 devices 

### ISSUE THREAD

**Issue by yvadher** [ibm-watson-iot/iot-nodejs#91]
Question, I am not sure if there is any other API call which can retrieve all devices. I am trying to get all devices of a specific type. I am using listAllDevicesOfType which is only returning first 100 devices.

**Comment by amitmangalvedkar** [comment]
You can use the pagination concept and keep iterating to get the next 100 devices.

**Comment by amitmangalvedkar** [comment]
In case you are satisfied with the pagination, could you please close the issue?

**Comment by yvadher** [comment]
Yes. Thank you
