### ISSUE TITLE
clients apparently giving up on reconnecting

### ISSUE THREAD

**Issue by iurly** [ibm-watson-iot/iot-nodejs#97]
Hi,
I'm experiencing some reconnection issues, see the whole story here:
https://github.com/ibm-watson-iot/node-red-contrib-ibm-watson-iot/issues/6

I can't be 100% sure, but I assume the problem might indeed be related to the client implementation (this repo) or the mqtt module used by the client.
Currently the mqtt module to be used is enforced to be version 1.5.0, and there's a slight chance the issue has been fixed already in any more recent version.
Assuming the problem might lie within the mqtt module, is there any chance we could upgrade to a more recent version?
Thanks!

**Comment by jeffdare** [comment]
Hi @iurly 
The latest version on ibmiotf, does use the [latest version of MQTT](https://github.com/ibm-watson-iot/iot-nodejs/blob/master/package.json#L15). So can you please update the version of ibmiotf in your raspberry pi to the latest. 

Regarding the reconnects issue, this module does try to reconnect if the client loses the connection.
It does a [staggered reconnect](https://github.com/ibm-watson-iot/iot-nodejs/blob/master/src/clients/BaseClient.js#L142) - 3, 10 and 60 seconds based on the number of retries.

**Comment by iurly** [comment]
Hi @jeffdare thanks for your feedback.
I will try to update ibmiotf then.
In the meantime, I was able to reproduce the issue in the lab.
What I did was add some iptables rules to selectively block traffic from my DNS servers so to emulate the behavior of what I'm seeing in the field.
This means it takes a lot of time (about one minute) to get a failure notification (getaddrinfo fails), before DNS resolution times out.
Here's a copy of my logs. As you can see, I get a failure notification about one minute after "Retrying connection", starting from the first attempt.
After exactly 10 failures (where the timeout values moves on to 60 seconds) I did not get any notification anymore.
Is it possible that the two timers are somehow interfering with each other, meaning that in this situation (DNS timeout) you get events in a different order than you normally would?
I also re-enable connectivity and the nodes have been offline for about 2 hours now, so it's not just a matter of error messages not being logged.
Incidentally, I get the same behavior in the field (10 failures and then complete silence).
So I suspect it might have something to do with the retrying logic.
Thanks again!

**Comment by jeffdare** [comment]
I think this is related to #25. It was fixed. Can you please try in the latest version of ibmiotf?

**Comment by iurly** [comment]
Updated ibmiotf to 0.2.39, the issue is apparently gone.
So it's very likely a duplicate of #25.
Closing the issue, thank you.
