### ISSUE TITLE
getAllHistoricalEvents keep returning 403

### ISSUE THREAD

**Issue by ZmartifyPKR** [ibm-watson-iot/iot-nodejs#99]
I keep getting error code 403 when trying to access historian data i.e. getAllHistoricalEvents(evtType,start,end) - I have Cloudant NoSQL historian data connected to Watson IoT and the data is available there.

I am using it from nodejs (ionic 3) and all the other api functions work smoothly...

**Comment by amitmangalvedkar** [comment]
@ZmartifyPKR : Historical Events APIs were not meant for events stored in external Cloudant. They were meant for built-in time-series historian data. This feature has been withdrawn. Refer to the [following link](https://developer.ibm.com/iotplatform/2016/07/27/notice-of-withdrawal-of-the-built-in-historian-component-of-ibm-watson-iot-platform/).

**Comment by Glagnar** [comment]
Thank you. When will you update the app to use the Cloudant API ?

**Comment by amitmangalvedkar** [comment]
@Glagnar : Currently there are no plans to support this on Cloudant or to update the app to use Cloudant API.   
We can, however, take this as a request and discuss with the design team of its feasibility and scope.

**Comment by amitmangalvedkar** [comment]
Can we close this issue? You can raise another issue for the support to Cloudant.

**Comment by ZmartifyPKR** [comment]
Thanks for the reply.
